// <auto-generated />
namespace CampusBookFlip.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CollegeDataAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollegeDataAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201401060114232_CollegeDataAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
