default:
  database:
    host: 'localhost'
    db: 'cbf-dev'
  redis:
    host: 'localhost'
    port: 6379
    secret: jv93n8x9wp9h3h98hqllwekno09j2nds302v8hzq9eg7stwhx54f2mv2bgd02j
development:
  database:
    host: 'localhost'
    db: 'cbf-dev'
  redis:
    host: 'localhost'
    port: 6379
    secret: jv93n8x9wp9h3h98hqllwekno09j2nds302v8hzq9eg7stwhx54f2mv2bgd02j
production:
  database:
    host: 'localhost'
    db: 'cbf-prd'
  redis:
    host: 'localhost'
    port: 6379
    secret: jv93n8x9wp9h3h98hqllwekno09j2nds302v8hzq9eg7stwhx54f2mv2bgd02j
